### ISSUE TITLE
Incompatible with valkyrien skies Mod on 1.20.1 Fabric

### ISSUE THREAD

**Issue by AClon314** [Benjamin-Norton/MCGPT#11]
Loaded Mods:
valkyrienskies-1201-2.3.0-beta.4.jar
mcchatgpt-fabric-0.2.1+1.20.jar
fabric-api-0.84.0+1.20.1.jar

Error Report:
[错误报告-2023.7.31_19.14.22.zip](https://github.com/Benjamin-Norton/MCChatGPT/files/12214418/-2023.7.31_19.14.22.zip)

**Comment by Bawnorton** [comment]
Crash was not caused by MCChatGPT, it is not in the stacktrace and MCChatGPT does not touch anything that Valkyrienskies does.
