### ISSUE TITLE
Version Support Question

### ISSUE THREAD

**Issue by Kasualix** [Benjamin-Norton/MCGPT#3]
do you plan to support 1165 forge?
If not, may I send you a PR to support it?

**Comment by Bawnorton** [comment]
I plan to support 1.19.2+ fabric and forge but didn't plan on backporting, however, there is an issue with forge gradle, NCDFE (no issue with fabric gradle), that prevents me from building a forge jar anyway. If you are able to find a way to get it to work in 1.16.5 architectury, that would be great.

**Comment by Kasualix** [comment]
Sorry but what's NCDFE?

**Comment by Bawnorton** [comment]
NoClassDefinitionFoundError

**Comment by Kasualix** [comment]
Failed.
Decide to write my own ChatGPT mod with my friends.
