### ISSUE TITLE
error communicating with open ai

### ISSUE THREAD

**Issue by Gabe2008** [Benjamin-Norton/MCGPT#5]
Whenever I use the /ask command it always respond with "An error occurred while communicating with OpenAI. Please check your internet connection, or try again later." I am connected to the internet and have tried multiple times but it still doesn't work.

![huge_2023-03-10_16 30 27](https://user-images.githubusercontent.com/90653423/224440355-ac55cbf1-bfb9-4c96-aed2-83e3f948c73e.png)

**Comment by Bawnorton** [comment]
can you hover over the chat message and tell me what it says.

**Comment by Gabe2008** [comment]
"You exceeded your current quota, please check your plan and billing details"

**Comment by Gabe2008** [comment]
I'm able to use chat GPT on its own though

**Comment by Bawnorton** [comment]
Your account's free period ended (https://platform.openai.com/account/usage). Web chatgpt is free to use for OpenAI's research but the API is not. Either setup a new openai account, you'll get an extra $18 worth of text for free, for the next quarter (you'll need a different phone number) or setup billing with your current account. The cost is about 0.0000005 USD per letter.
