### ISSUE TITLE
Updating the information the MCChatGPT can access

### ISSUE THREAD

**Issue by Dracnoian** [Benjamin-Norton/MCGPT#9]
Please forgive me if this question is absolutely idiotic, I do not know much about how creating something that accesses OpenAI works, but: how come MCChatGPT uses the training data from around 1.17? Is this the only data they have made available to use for this type of program, and will MCChatGPT be able to upgrade in the future?

I absolutely love this mod so far. Having this little AI in my pocket in-game is so strangely helpful and fun at the same time. Thank you for bringing this to us.

**Comment by Bawnorton** [comment]
ChatGPT is a large language model which is trained by scraping the web and extracting the text from millions of websites. This model has 1 billion parameters (which is a lot) but it finished training in 2021, thus, it doesn't know much beyond 1.17. You can provide it with information to help you answer questions and I am currently working on adding an option to increase the amount of context you can give the model automatically such that it knows about the world.

**Comment by Bawnorton** [comment]
You can read more on it here https://openai.com/blog/chatgpt
